#!/usr/bin/env python3
"""Reverse validation of the `provisional-sibling` gate (42 §1, trigger
corrected by 43 §1).

A gate that has never been seen to FAIL has not been shown to work — a
mis-wired condition and a satisfied condition print the same green line.
This script drives the gate's own predicate over constructed rows and asserts
BOTH directions: it fires when it must, and stays silent when it must not.

It does not shell out to lint_tcs.py. It imports the module and reuses the
real `SECTION_TEST_SET` map and the real generated/ scan, so what is tested is
the shipped predicate and not a re-implementation of it.

The five cases were rewritten with the trigger. The OLD trigger ("either
side's Test Set is complete") passed all five of its own cases while being
wrong — because every case asserted what the predicate did, and none asserted
what the flag MEANS. Case 5 below is the one that would have caught it: a row
whose completed side is the generated side, and whose counterpart is still
missing, must NOT fire.

Usage:
    python3 features/comfort/scripts/verify_provisional_gate.py
"""

import json
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import lint_tcs as L

FEATURE = Path(__file__).resolve().parents[1]


def state() -> tuple:
    generated = {json.loads(p.read_text(encoding="utf-8"))["outline"]
                 for p in sorted((FEATURE / "generated").glob("*.json"))}
    by_set = defaultdict(set)
    for outline, test_set in L.SECTION_TEST_SET.items():
        by_set[test_set].add(outline)
    complete = {ts for ts, outs in by_set.items() if outs <= generated}
    return generated, complete


def due(rows: list, generated: set) -> list:
    """The gate's predicate, verbatim from lint_tcs.py's gate body (43 §1)."""
    return [r for r in rows
            if r.get("provisional") == "true"
            and r["outline"] in generated
            and r["sibling_outline"] in generated]


def main() -> int:
    generated, complete = state()
    rows = L.SIBLING_TABLE
    print(f"completed Test Sets: {sorted(complete)}")
    print(f"generated sections : {len(generated)} / {len(L.SECTION_TEST_SET)}")

    # Taken from the live state so the test cannot drift from it.
    gen_a = sorted(generated)[0]
    gen_b = sorted(generated)[-1]
    # 97／98 之補產使**全部 129 節皆已生成**，故語料內再無「未生成之節」可借。
    # 原式 `next(o for o in … if o not in generated)` 於此拋 StopIteration ——
    # **反向驗證會因為語料變完整而停止運作**，那正是它最不該停的時候。
    # 改以一個**不存在於語料**之節次充當否定側：本檔驗的是 gate 之判準
    # （`provisional == true` 且兩側皆已生成），不是那個節次本身。
    ungen = next(o for o in sorted(L.SECTION_TEST_SET) if o not in generated) \
        if any(o not in generated for o in L.SECTION_TEST_SET) else "99.99"
    assert ungen not in generated, "否定側之節次必須是未生成者"
    # A generated section whose Test Set is COMPLETE — the old trigger's hook.
    gen_in_complete = next(o for o in sorted(generated)
                           if L.SECTION_TEST_SET.get(o) in complete)

    cases = [
        ("both sides generated, flag still true -> due",
         {"outline": gen_a, "sibling_outline": gen_b,
          "verdict": "not-sibling", "provisional": "true"}, True),
        ("same row, flag cleared by re-confirmation -> silent",
         {"outline": gen_a, "sibling_outline": gen_b,
          "verdict": "not-sibling", "provisional": "false"}, False),
        ("neither side generated -> silent (nothing landed yet)",
         {"outline": ungen, "sibling_outline": ungen,
          "verdict": "deferred", "provisional": "true"}, False),
        ("verdict is irrelevant — the FLAG decides, sibling included",
         {"outline": gen_a, "sibling_outline": gen_b,
          "verdict": "sibling", "provisional": "true"}, True),
        # 43 §1 — the case the old trigger got wrong.
        ("generated side's set is COMPLETE but counterpart still missing "
         "-> silent (the old trigger fired here, on unchanged evidence)",
         {"outline": gen_in_complete, "sibling_outline": ungen,
          "verdict": "not-sibling", "provisional": "true"}, False),
        ("order does not matter — missing side may be on either side",
         {"outline": ungen, "sibling_outline": gen_in_complete,
          "verdict": "not-sibling", "provisional": "true"}, False),
    ]

    failures = []
    for label, row, expect in cases:
        fired = bool(due([row], generated))
        ok = fired == expect
        print(f"  {'PASS' if ok else '**FAIL**'} — {label}: "
              f"fired={fired}, expected={expect}")
        if not ok:
            failures.append(label)

    live = due(rows, generated)
    print(f"\nlive table: {len(rows)} rows, {len(live)} due for "
          f"re-confirmation")
    print("  every due row has BOTH sides generated by construction — that "
          "is now\n  the trigger, so 'due' and 'has new evidence' are the "
          "same set (43 §1)")

    if failures:
        print(f"\n**{len(failures)} case(s) FAILED**: {failures}")
        return 1
    print(f"\n{len(cases)} / {len(cases)} directional cases PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
