"""第五批產生器（R-P181）。

範圍**取自 G121 對帳表**，依 R-P177(b) 逐一列出 leaf ID 全集，
**不以 ID 區間表述**。`leaves` 之 `section` / `source_anchor` /
`source_clause` 全部機械取得（`build_b5_material.py` 同源）。

TC 內容為人所撰（下表 `TCS`），拆分依 §5.7 / §8.2.2；
`tc_id` 為批次內臨時號（R-P113(b)），接續第四批之末（`157`）。

用法：
    python features/power/scripts/gen_batch05.py
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
DATA = ROOT / "features/power/data"
GENERATED = ROOT / "features/power/generated"

sys.path.insert(0, str(Path(__file__).resolve().parent))
from build_b5_material import layer3, scope  # noqa: E402
from lint_tcs import anchor_bodies  # noqa: E402

SPEC = ("R1LR_Atl-H_25PI3.5_Activation and Configuration_"
        "CFTS_009_Wake-up and Power-up_SR26_20250909-1658")
SIM = "A LIN and CAN simulation tool is connected"
START_ID = 158
BATCH = "batch_005_startup_display"

# 與他 leaf 共用**全部**錨點者 —— `source_clause` 逐字相同（見上繳 §五）。
DUP_NOTE = {
    "SWE-PM-097": "SWE-PM-056",
    "SWE-PM-101": "SWE-PM-054",
    "SWE-PM-102": "SWE-PM-055",
    "SWE-PM-114": "SWE-PM-068",
    "SWE-PM-115": "SWE-PM-070",
}
NOTES = {
    leaf: (f"**本 leaf 之 `source_anchor` 與 `{other}` 完全相同**，"
           f"`source_clause` 逐字一致。執行層**未合併、未省略**，"
           f"依 037 之 leaf 母體逐一產出以維持追溯；"
           f"是否應改依 §8.2.1 委由 `{other}` 承擔，**呈請裁定於 26 包**。")
    for leaf, other in DUP_NOTE.items()
}
NOTES["SWE-PM-093"] = (
    "**本 leaf 之二錨點（`4941301` §1.3.5 / `4941941` §1.9.8）內文逐字相同，"
    "而屬性相異五欄**（ECU / EE Architecture / Model Year / Radio / State）——"
    "為 R-P136 所定之「屬性相異 → 停並上繳」形態。"
    "二者之 ECU 皆含 `LTM`、Radio 皆涵蓋本專案，故適用性未變，TC 照常產出；"
    "**是否為變體登載，呈請裁定於 26 包**。")

# leaf -> [(title, pre[], data, proc[], er[], priority, split_reason)]
TCS: dict[str, list[tuple]] = {
    "SWE-PM-066": [
        ("An SOS call is treated as a phone call becoming active",
         [SIM, "The HU is in a state that reacts to a phone call becoming active"],
         "An SOS call is placed",
         ["Place the call listed in Input Test Data",
          "Read the HU reaction to check that it treats the call as a phone call"],
         ["The HU registers the call",
          "The HU behaves as for a Phone call becoming active"],
         "P0", "本條驗 SOS call"),
        ("An Assist call is treated as a phone call becoming active",
         [SIM, "The HU is in a state that reacts to a phone call becoming active"],
         "An Assist call is placed",
         ["Place the call listed in Input Test Data",
          "Read the HU reaction to check that it treats the call as a phone call"],
         ["The HU registers the call",
          "The HU behaves as for a Phone call becoming active"],
         "P0", "本條驗 Assist call"),
    ],
    "SWE-PM-067": [
        ("A projection device call is treated as a phone call becoming active",
         [SIM, "A projection device is paired on the bench"],
         "A Projection device call is placed",
         ["Place the call listed in Input Test Data",
          "Read the HU reaction to check that it treats the call as a phone call"],
         ["The HU registers the call",
          "The HU behaves as for a Phone call becoming active"],
         "P0", "本條驗 Projection device call"),
    ],
    "SWE-PM-068": [
        ("An incoming call from IDLE bypasses the disclaimer screen",
         [SIM, "The HU is in IDLE mode", "The disclaimer screen has not yet been shown"],
         "An incoming phone call",
         ["Let the bench place the call listed in Input Test Data",
          "Read the HU mode and the screen to check whether the disclaimer appears"],
         ["The HU transitions from IDLE to FULL OPERATION",
          "The disclaimer screen is bypassed"],
         "P0", "本條驗來電所致之 IDLE → FULL OPERATION 免顯免責畫面"),
    ],
    "SWE-PM-069": [
        ("The HU returns to IDLE when the call ends on the phone main screen",
         [SIM, "The HU is in IDLE mode", "The display is on the phone main screen"],
         "An incoming phone call that then becomes inactive",
         ["Let the bench place and then end the call listed in Input Test Data",
          "Read the HU mode to check the transition after the call ends"],
         ["The HU transitions from IDLE to FULL OPERATION for the call",
          "The HU transitions back to IDLE"],
         "P0", "本條驗 OR 之左支 phone main screen"),
        ("The HU returns to IDLE when the call ends on the phone projection call UI",
         [SIM, "The HU is in IDLE mode", "The display is on the phone projection call UI"],
         "An incoming phone call that then becomes inactive",
         ["Let the bench place and then end the call listed in Input Test Data",
          "Read the HU mode to check the transition after the call ends"],
         ["The HU transitions from IDLE to FULL OPERATION for the call",
          "The HU transitions back to IDLE"],
         "P0", "本條驗 OR 之右支 phone projection call UI"),
    ],
    "SWE-PM-070": [
        ("The bypassed disclaimer is shown at the next transition to FULL OPERATION",
         [SIM, "The HU is in IDLE mode", "The disclaimer has not yet been shown"],
         "An incoming phone call that then becomes inactive",
         ["Let the bench place and then end the call listed in Input Test Data",
          "Bring the HU to FULL OPERATION again and read the screen to check the disclaimer"],
         ["The HU bypasses the disclaimer for the call and returns to IDLE",
          "The disclaimer is shown at the next transition to FULL OPERATION"],
         "P0", "本條驗免責畫面之延後補顯"),
    ],
    "SWE-PM-074": [
        ("A Radio FOTA update at Body OFF brings the HU to Timed for the pop-up",
         [SIM, "The HU transitions to Standby mode as the vehicle enters Body OFF mode"],
         "A FOTA update available for the Radio",
         ["Make available the update listed in Input Test Data",
          "Read the HU mode and the screen to check the resulting presentation"],
         ["The HU transitions to Timed mode",
          "The FOTA update available pop-up is displayed"],
         "P0", "本條驗 OR 之 Radio 支"),
        ("A TBM FOTA update at Body OFF brings the HU to Timed for the pop-up",
         [SIM, "The HU transitions to Standby mode as the vehicle enters Body OFF mode"],
         "A FOTA update available for the TBM",
         ["Make available the update listed in Input Test Data",
          "Read the HU mode and the screen to check the resulting presentation"],
         ["The HU transitions to Timed mode",
          "The FOTA update available pop-up is displayed"],
         "P0", "本條驗 OR 之 TBM 支"),
        ("A ROV FOTA update at Body OFF brings the HU to Timed for the pop-up",
         [SIM, "The HU transitions to Standby mode as the vehicle enters Body OFF mode"],
         "A FOTA update available for the ROV",
         ["Make available the update listed in Input Test Data",
          "Read the HU mode and the screen to check the resulting presentation"],
         ["The HU transitions to Timed mode",
          "The FOTA update available pop-up is displayed"],
         "P0", "本條驗 OR 之 ROV 支"),
    ],
    "SWE-PM-075": [
        ("The HU leaves Timed one minute after the FOTA pop-up is left untouched",
         [SIM, "The HU is in Timed mode due to the condition described in CFTS009-1809"],
         "NA",
         ["Leave the FOTA pop-up without any user interaction",
          "Read the HU mode after the idle period to check the transition"],
         ["The pop-up stays on the screen while no interaction occurs",
          "The HU transitions to Standby mode after 1 minute has passed"],
         "P0", "本條驗條件一 —— 1 分鐘無互動"),
        ("The HU leaves Timed when the FOTA pop-up is dismissed",
         [SIM, "The HU is in Timed mode due to the condition described in CFTS009-1809"],
         "NA",
         ["Dismiss the FOTA pop-up on the screen",
          "Read the HU mode to check the transition after the dismissal"],
         ["The FOTA pop up is dismissed",
          "The HU transitions to Standby mode"],
         "P0", "本條驗條件二 —— pop-up 被關閉"),
        ("The HU leaves Timed when the accessory delay becomes inactive",
         [SIM, "The HU is in Timed mode due to the condition described in CFTS009-1809"],
         "$ACCDlyAct$: active to inactive",
         ["Send the transition listed in Input Test Data",
          "Read the HU mode to check the transition that follows"],
         ["The HU registers the transition without a bus error",
          "The HU transitions to Standby mode"],
         "P0", "本條驗條件三 —— $ACCDlyAct$ 轉為 inactive"),
    ],
    "SWE-PM-076": [
        ("A ten second power button press performs a radio reset and saves logs",
         [SIM, "The HU is not installing a firmware image"],
         "$ICSPowerButton$: Pressed for 10 seconds consecutively",
         ["Send the input listed in Input Test Data",
          "Read the HU behavior and the stored logs to check the reset"],
         ["The HU performs a radio reset",
          "The HU collects and saves logs at the time of the reset"],
         "P0", "本條驗重置本身與 log 保存"),
        ("The power button reset covers both the main CPU and the CAN micro",
         [SIM, "The HU is not installing a firmware image"],
         "$ICSPowerButton$: Pressed for 10 seconds consecutively",
         ["Send the input listed in Input Test Data",
          "Read both processors to check what the reset covers"],
         ["The main CPU resets at the time of the reset",
          "The CAN micro resets at the time of the reset"],
         "P0", "本條驗重置範圍涵蓋二個處理器"),
        ("No power button reset occurs while a firmware image is installing",
         [SIM, "The HU is currently installing a firmware image"],
         "$ICSPowerButton$: Pressed for 10 seconds consecutively",
         ["Send the input listed in Input Test Data",
          "Read the HU behavior to check whether a reset occurs"],
         ["The HU registers the input",
          "The HU does not reset due to a power button reset"],
         "P1", "本條驗韌體安裝中之例外"),
    ],
    "SWE-PM-093": [
        ("Closing the driver door in SLEEP MODE plays the start-up animation",
         [SIM, "The HU is in SLEEP MODE", "A driver door is present for the vehicle"],
         '$Door_Ajar_Status$: changed to CLOSED',
         ["Send the change listed in Input Test Data",
          "Read the screen to check the start-up animation defined per HMI"],
         ["The HU registers the change without a bus error",
          "The HU plays a start-up animation"],
         "P0", "本條驗 OR 之 SLEEP MODE 支"),
        ("Closing the driver door in STANDBY MODE plays the start-up animation",
         [SIM, "The HU is in STANDBY MODE", "A driver door is present for the vehicle"],
         '$Door_Ajar_Status$: changed to CLOSED',
         ["Send the change listed in Input Test Data",
          "Read the screen to check the start-up animation defined per HMI"],
         ["The HU registers the change without a bus error",
          "The HU plays a start-up animation"],
         "P0", "本條驗 OR 之 STANDBY MODE 支"),
        ("Closing the driver door in PARTIAL OPERATION MODE plays the start-up animation",
         [SIM, "The HU is in PARTIAL OPERATION MODE", "A driver door is present for the vehicle"],
         '$Door_Ajar_Status$: changed to CLOSED',
         ["Send the change listed in Input Test Data",
          "Read the screen to check the start-up animation defined per HMI"],
         ["The HU registers the change without a bus error",
          "The HU plays a start-up animation"],
         "P0", "本條驗 OR 之 PARTIAL OPERATION MODE 支"),
        ("A removed driver door makes the HU skip the start-up animation",
         [SIM, "The HU is in STANDBY MODE"],
         '$DriverDoorOnOffSts$: "DOOR_OFF"',
         ["Send the value listed in Input Test Data and close the driver door",
          "Read the screen to check whether an animation is played"],
         ["The HU registers the value without a bus error",
          "The HU skips the start-up animation"],
         "P0", "本條驗 $DriverDoorOnOffSts$ 之略過分支"),
        ("A mode change cancels a start-up animation in progress",
         [SIM, "The HU is playing a start-up animation"],
         "An ignition event that changes the HU power mode to BODY ON",
         ["Send the event listed in Input Test Data during the animation",
          "Read the screen and the power mode to check the cancellation"],
         ["The HU cancels the current start-up animation",
          "The HU switches to the required power mode as defined"],
         "P0", "本條驗播放中之模式變更取消"),
        ("An ignition crank event cancels a start-up animation in progress",
         [SIM, "The HU is playing a start-up animation"],
         '$PowerMode$: "IGN_START"',
         ["Send the value listed in Input Test Data during the animation",
          "Read the screen and the power mode to check the cancellation"],
         ["The HU cancels the current start-up animation",
          "The HU switches to the required power mode as defined"],
         "P0", "本條驗 IGN_START 取消"),
        ("A mode change to TIMED MODE cancels a start-up animation in progress",
         [SIM, "The HU is playing a start-up animation"],
         "An HU power mode status change to TIMED MODE",
         ["Send the change listed in Input Test Data during the animation",
          "Read the screen and the power mode to check the cancellation"],
         ["The HU cancels the current start-up animation",
          "The HU switches to the required power mode as defined"],
         "P0", "本條驗 OR 之 TIMED MODE 支（R-P118(d) 反向涵蓋裁決補測）"),
        ("An open driver door makes the HU skip the animation on a mode change",
         [SIM, "The HU is in STANDBY MODE",
          '$Door_Ajar_Status$ reads OPEN'],
         "An HU power mode status change to BODY ON",
         ["Send the change listed in Input Test Data",
          "Read the screen to check whether an animation is played"],
         ["The HU switches to the required power mode",
          "The HU skips the start-up animation"],
         "P0", "本條驗門開啟時之模式變更略過（R-P118(d) 反向涵蓋裁決補測）"),
        ("A second start-up animation waits for the wakeup cycle or thirty minutes",
         [SIM, "The HU has just played a start-up animation",
          "All other conditions for the animation to play are met"],
         "NA",
         ["Close the driver door again within the same CAN wakeup cycle",
          "Read the screen against the elapsed time to check the replay rule"],
         ["No further start-up animation is played",
          "A start-up animation plays again only at the next CAN wakeup cycle or after 30 minutes, whichever is greater"],
         "P1", "本條驗再播放之間隔規則"),
    ],
    "SWE-PM-094": [
        ("The startup animation is displayed separately from the other startup screens",
         [SIM, "The HU is in STANDBY MODE"],
         "NA",
         ["Bring the HU through a startup that plays the animation",
          "Read the screen sequence to check how the animation is presented"],
         ["The startup animation is displayed",
          "The startup animation is displayed separately from the Splash screen and disclaimer screen"],
         "P1", "本條驗三畫面之分離呈現"),
    ],
    "SWE-PM-095": [
        ("Leaving the SNA value resumes the state diagram without a splash screen",
         [SIM, 'LTM_OperationalModeSts.Info reads "SNA"'],
         'LTM_OperationalModeSts.Info: a value different from "SNA"',
         ["Send the value listed in Input Test Data",
          "Read the TLM state and the screen to check the resumed behavior"],
         ["The TLM follows the state diagram using the updated value",
          "The possible visualization of the splash screen is avoided"],
         "P0", "本條驗離開 SNA 之恢復行為"),
    ],
    "SWE-PM-097": [
        ("The Fiat Latam startup animation selection replaces the vehicle brand logo",
         [SIM, "The HU carries a configured vehicle brand"],
         'DID "Startup Animation Selection": "Fiat Latam"',
         ["Send the value listed in Input Test Data",
          "Read the shown logo against the configured brand to check which logo appears"],
         ["The HU accepts the configuration value",
          "The Fiat Latam Logo replaces the vehicle brand logo regardless of the configured brand"],
         "P1", "本條驗 Fiat Latam 之覆蓋規則"),
    ],
    "SWE-PM-098": [
        ("The always setting plays a startup sound with the animation",
         [SIM, '$Themed_Sound$ reads "Fiat Latam"',
          'The "Welcome Onboard Sound" setting reads "Always"'],
         "NA",
         ["Bring the HU through a startup that plays the animation",
          "Read the audio output against the animation start to check the accompaniment"],
         ["The HU startup animation is played",
          "A startup sound accompanies the animation and begins at the same time"],
         "P0", "本條驗 Always 設定"),
    ],
    "SWE-PM-099": [
        ("The once a day setting plays the startup sound on the first startup of the day",
         [SIM, '$Themed_Sound$ reads "Fiat Latam"',
          'The "Welcome Onboard Sound" setting reads "Once a Day"',
          "The HU has not yet played the startup sound that day"],
         "NA",
         ["Bring the HU through a startup that plays the animation",
          "Read the audio output against the animation start to check the accompaniment"],
         ["The HU startup animation is played",
          "A startup sound accompanies the animation and begins at the same time"],
         "P0", "本條驗 Once a Day 之當日首次"),
        ("A change of the customer selected date allows the sound to play again",
         [SIM, '$Themed_Sound$ reads "Fiat Latam"',
          'The "Welcome Onboard Sound" setting reads "Once a Day"',
          "The HU has already played the startup sound that day"],
         "A manual time adjustment that changes the customer selected date",
         ["Send the adjustment listed in Input Test Data and start the HU again",
          "Read the audio output to check whether a new day is granted"],
         ["The HU startup animation is played",
          "A startup sound accompanies the animation for the new day"],
         "P1", "本條驗「新的一天」之判定 —— 手動調整"),
        ("Passing midnight allows the startup sound to play again",
         [SIM, '$Themed_Sound$ reads "Fiat Latam"',
          'The "Welcome Onboard Sound" setting reads "Once a Day"',
          "The HU has already played the startup sound that day"],
         "NA",
         ["Let the clock pass midnight and start the HU again",
          "Read the audio output to check whether a new day is granted"],
         ["The HU startup animation is played",
          "A startup sound accompanies the animation for the new day"],
         "P1", "本條驗「新的一天」之判定 —— 跨越午夜（R-P118(d) 補測）"),
        ("An automatic time zone adjustment allows the startup sound to play again",
         [SIM, '$Themed_Sound$ reads "Fiat Latam"',
          'The "Welcome Onboard Sound" setting reads "Once a Day"',
          "The HU has already played the startup sound that day"],
         "An automatic adjustment due to time zones or Daylight Savings Time",
         ["Send the adjustment listed in Input Test Data and start the HU again",
          "Read the audio output to check whether a new day is granted"],
         ["The HU startup animation is played",
          "A startup sound accompanies the animation for the new day"],
         "P1", "本條驗「新的一天」之判定 —— 時區／日光節約自動調整（R-P118(d) 補測）"),
    ],
    "SWE-PM-100": [
        ("The never setting plays no startup sound with the animation",
         [SIM, '$Themed_Sound$ reads "Fiat Latam"',
          'The "Welcome Onboard Sound" setting reads "Never"'],
         "NA",
         ["Bring the HU through a startup that plays the animation",
          "Read the audio output against the animation start to check the accompaniment"],
         ["The HU startup animation is played",
          "No startup sound accompanies the animation"],
         "P0", "本條驗 Never 設定"),
    ],
    "SWE-PM-101": [
        ("No audio brand without SDARS shows the vehicle brand logo only",
         [SIM, 'SDARS_Presence reads "Absent"'],
         'Audio_Brand: "No Audio Brand"',
         ["Send the value listed in Input Test Data",
          "Read the shown logos to check the resulting presentation"],
         ["The brand logo screen is presented",
          "The vehicle brand logo that depends on the Brand_Configuration_2 parameter value is shown alone"],
         "P0", "本條驗組合一（Absent ＋ No Audio Brand）"),
        ("Beats brand white without SDARS adds the Beats logo",
         [SIM, 'SDARS_Presence reads "Absent"'],
         'Audio_Brand: "Beats Brand White"',
         ["Send the value listed in Input Test Data",
          "Read the shown logos to check the resulting presentation"],
         ["The brand logo screen is presented",
          "The Beats Brand White logo is shown in addition to the vehicle brand logo"],
         "P0", "本條驗組合二（Absent ＋ Beats Brand White）"),
        ("SDARS present without audio brand adds the Sirius logo",
         [SIM, 'SDARS_Presence reads "Present"'],
         'Audio_Brand: "No Audio Brand"',
         ["Send the value listed in Input Test Data",
          "Read the shown logos to check the resulting presentation"],
         ["The brand logo screen is presented",
          "The Sirius logo is shown in addition to the vehicle brand logo"],
         "P0", "本條驗組合三（Present ＋ No Audio Brand）"),
        ("SDARS present with beats brand white adds both logos",
         [SIM, 'SDARS_Presence reads "Present"'],
         'Audio_Brand: "Beats Brand White"',
         ["Send the value listed in Input Test Data",
          "Read the shown logos to check the resulting presentation"],
         ["The brand logo screen is presented",
          "Both the Sirius and the Beats logos are shown in addition to the vehicle brand logo"],
         "P0", "本條驗組合四（Present ＋ Beats Brand White）"),
    ],
    "SWE-PM-102": [
        ("The special package drives the Klipsch Splash Screen on the 2025 model year",
         [SIM, 'The ETM carries $VC_MODEL_YEAR$ equal to "2025"',
          'The ETM carries $VC_VEH_LINE$ equal to "DT"'],
         '$VC_SpecialPKG_IC$: "Tungsten (147)"',
         ["Send the value listed in Input Test Data",
          "Read the shown Splash Screen to check which screen the ETM displays"],
         ["The ETM accepts the configuration value",
          "The Klipsch Splash Screen is displayed"],
         "P1", "本條驗 2025 年式之 $VC_SpecialPKG_IC$ 路徑"),
        ("The splash screen type drives the Klipsch Splash Screen after the 2025 model year",
         [SIM, 'The ETM carries $VC_MODEL_YEAR$ greater than "2025"',
          'The ETM carries $VC_VEH_LINE$ equal to "DT"'],
         '$SplashScreen_Type$: "Klipsch (7)"',
         ["Send the value listed in Input Test Data",
          "Read the shown Splash Screen to check which screen the ETM displays"],
         ["The ETM accepts the configuration value",
          "The Klipsch Splash Screen is displayed"],
         "P1", "本條驗 2025 年式之後之 $SplashScreen_Type$ 路徑"),
    ],
    "SWE-PM-103": [
        ("Audio is off and only the Splash Screen is allowed in this status",
         [SIM, "The TLM is in an Ignition On working condition"],
         "NA",
         ["Bring the TLM to the status related to TLM audio is OFF",
          "Read the audio path and the display to check what is allowed"],
         ["The TLM audio is OFF",
          "The TLM allows only Splash Screen visualization on its display"],
         "P0", "本條驗音訊關閉與畫面限制"),
        ("ICS stays available while DTV is off in this status",
         [SIM, "The TLM is in an Ignition On Engine On working condition"],
         "NA",
         ["Bring the TLM to the status related to TLM audio is OFF",
          "Read the ICS functions and the DTV to check their availability"],
         ["ICS functionalities are available",
          "DTV is OFF"],
         "P1", "本條驗 ICS 與 DTV 之可用性"),
    ],
    "SWE-PM-104": [
        ("The splash and disclaimer screens appear on the first transition to Timed",
         [SIM, "A new bus cycle has started",
          "Neither screen has been shown in this bus cycle"],
         "NA",
         ["Bring the HU to Timed mode for the first time in the bus cycle",
          "Read the screen sequence to check both startup screens"],
         ["The splash screen is shown",
          "The disclaimer screen is shown"],
         "P0", "本條驗首次進入 Timed"),
        ("The splash and disclaimer screens appear on the first transition to Full Operation",
         [SIM, "A new bus cycle has started",
          "Neither screen has been shown in this bus cycle"],
         "NA",
         ["Bring the HU to Full Operation mode for the first time in the bus cycle",
          "Read the screen sequence to check both startup screens"],
         ["The splash screen is shown",
          "The disclaimer screen is shown"],
         "P0", "本條驗首次進入 Full Operation"),
        ("The disclaimer appears on the first transition from Idle",
         [SIM, "The HU is in Idle mode", "The disclaimer needs to be shown"],
         "NA",
         ["Bring the HU from Idle to Timed mode for the first time in the bus cycle",
          "Read the screen to check the disclaimer presentation"],
         ["The HU reaches Timed mode",
          "The disclaimer screen is shown"],
         "P0", "本條驗來源狀態 Idle"),
        ("The disclaimer appears on the first transition from Standby",
         [SIM, "The HU is in Standby mode", "The disclaimer needs to be shown"],
         "NA",
         ["Bring the HU from Standby to Timed mode for the first time in the bus cycle",
          "Read the screen to check the disclaimer presentation"],
         ["The HU reaches Timed mode",
          "The disclaimer screen is shown"],
         "P0", "本條驗來源狀態 Standby"),
        ("The disclaimer appears on the first transition from Partial Operation",
         [SIM, "The HU is in Partial Operation mode", "The disclaimer needs to be shown"],
         "NA",
         ["Bring the HU from Partial Operation to Full Operation for the first time",
          "Read the screen to check the disclaimer presentation"],
         ["The HU reaches Full Operation mode",
          "The disclaimer screen is shown"],
         "P0", "本條驗來源狀態 Partial Operation"),
    ],
    "SWE-PM-105": [
        ("An ongoing call temporarily skips the disclaimer and splash screens",
         [SIM, "A new bus cycle has started"],
         "An ongoing call at the moment of the transition",
         ["Bring the HU to Timed mode while the event listed in Input Test Data holds",
          "Read the screen to check whether the startup screens appear"],
         ["The HU reaches Timed mode",
          "The disclaimer and splash screen are temporarily skipped"],
         "P0", "本條驗通話類之暫時略過"),
        ("A backup camera view temporarily skips the disclaimer and splash screens",
         [SIM, "A new bus cycle has started"],
         "A backup camera view at the moment of the transition",
         ["Bring the HU to Timed mode while the event listed in Input Test Data holds",
          "Read the screen to check whether the startup screens appear"],
         ["The HU reaches Timed mode",
          "The disclaimer and splash screen are temporarily skipped"],
         "P1", "本條驗非通話類之暫時略過"),
        ("An incoming call temporarily skips the disclaimer and splash screens",
         [SIM, "A new bus cycle has started"],
         "An incoming call at the moment of the transition",
         ["Bring the HU to Timed mode while the event listed in Input Test Data holds",
          "Read the screen to check whether the startup screens appear"],
         ["The HU reaches Timed mode",
          "The disclaimer and splash screen are temporarily skipped"],
         "P1", "本條驗 incoming call 支（R-P118(d) 補測）"),
        ("An outgoing call temporarily skips the disclaimer and splash screens",
         [SIM, "A new bus cycle has started"],
         "An outgoing call at the moment of the transition",
         ["Bring the HU to Timed mode while the event listed in Input Test Data holds",
          "Read the screen to check whether the startup screens appear"],
         ["The HU reaches Timed mode",
          "The disclaimer and splash screen are temporarily skipped"],
         "P1", "本條驗 outgoing call 支（R-P118(d) 補測）"),
        ("A climate pop-up temporarily skips the disclaimer and splash screens",
         [SIM, "A new bus cycle has started"],
         "A climate pop-up at the moment of the transition",
         ["Bring the HU to Timed mode while the event listed in Input Test Data holds",
          "Read the screen to check whether the startup screens appear"],
         ["The HU reaches Timed mode",
          "The disclaimer and splash screen are temporarily skipped"],
         "P1", "本條驗 climate pop-ups 支（R-P118(d) 補測）"),
        ("An SOS or Assist call temporarily skips the disclaimer and splash screens",
         [SIM, "A new bus cycle has started"],
         "An SOS or Assist call at the moment of the transition",
         ["Bring the HU to Timed mode while the event listed in Input Test Data holds",
          "Read the screen to check whether the startup screens appear"],
         ["The HU reaches Timed mode",
          "The disclaimer and splash screen are temporarily skipped"],
         "P1", "本條驗 SOS and Assist calls 支（R-P118(d) 補測）"),
        ("A FOTA pop up temporarily skips the disclaimer and splash screens",
         [SIM, "A new bus cycle has started"],
         "A FOTA pop up at the moment of the transition",
         ["Bring the HU to Timed mode while the event listed in Input Test Data holds",
          "Read the screen to check whether the startup screens appear"],
         ["The HU reaches Timed mode",
          "The disclaimer and splash screen are temporarily skipped"],
         "P1", "本條驗 FOTA pop ups 支（R-P118(d) 補測）"),
        ("The skipped screens are displayed at the next transition in the bus cycle",
         [SIM, "The startup screens were skipped earlier in this bus cycle"],
         "NA",
         ["Bring the HU to Full Operation mode again within the same bus cycle",
          "Read the screen to check the deferred presentation"],
         ["The HU reaches Full Operation mode",
          "The skipped screens are displayed at this transition"],
         "P0", "本條驗延後補顯之義務"),
    ],
    "SWE-PM-106": [
        ("The SOS button variant selects the SOS disclaimer text",
         [SIM, "The HU is configured for a disclaimer screen variation"],
         '$Ecall_Button_Variant$: "SOS"',
         ["Send the value listed in Input Test Data",
          "Read the disclaimer wording to check which text the HU uses"],
         ["The HU accepts the configuration value",
          "The HU uses the SOS text for the disclaimer"],
         "P0", "本條驗 SOS 變體"),
    ],
    "SWE-PM-107": [
        ("The help button variant replaces the SOS text in the disclaimer",
         [SIM, "The HU is configured for a disclaimer screen variation"],
         '$Ecall_Button_Variant$: "Help"',
         ["Send the value listed in Input Test Data",
          "Read the disclaimer wording to check which text the HU uses"],
         ["The HU accepts the configuration value",
          'The HU replaces the "SOS" text with the "Help" version of the disclaimer'],
         "P0", "本條驗 Help 變體"),
    ],
    "SWE-PM-108": [
        ("A non Maserati brand shows the core disclaimer once every thirty ignition cycles",
         [SIM, '$VC_VEH_BRAND$ reads a value other than "Maserati"'],
         "NA",
         ["Run the head unit through consecutive ignition cycles",
          "Read the screen across the cycles to check how often the disclaimer appears"],
         ["The core disclaimer screen is shown on the first ignition cycle",
          "The core disclaimer screen is shown only once every 30 ignition cycles"],
         "P0", "本條驗免責畫面之顯示頻率"),
    ],
    "SWE-PM-109": [
        ("A GDPR market with the TBM present follows the GDPR non Maserati startup flow",
         [SIM, '$VC_VEH_BRAND$ reads a value other than "Maserati"',
          '$TBM_Present$ reads "Present"',
          "$Country_Code$ is marked as a country needing the combined Geolocation plus SOS Popup"],
         "NA",
         ["Bring the HU through the startup sequence",
          "Read the startup flow against the HMI to check which flow is followed"],
         ["The HU reaches the startup presentation",
          "The HU follows the GDPR Non-Maserati startup flow in the HMI"],
         "P0", "本條驗 GDPR 流程"),
    ],
    "SWE-PM-110": [
        ("A missing TBM follows the non GDPR non Maserati startup flow",
         [SIM, '$VC_VEH_BRAND$ reads a value other than "Maserati"',
          '$TBM_Present$ reads "Not Present"'],
         "NA",
         ["Bring the HU through the startup sequence",
          "Read the startup flow against the HMI to check which flow is followed"],
         ["The HU reaches the startup presentation",
          "The HU follows the Non-GDPR/Non-Maserati Startup flow in the HMI"],
         "P0", "本條驗 OR 之左支 TBM Not Present"),
        ("An unmarked country follows the non GDPR non Maserati startup flow",
         [SIM, '$VC_VEH_BRAND$ reads a value other than "Maserati"',
          '$TBM_Present$ reads "Present"',
          '$Country_Code$ is not marked as one of the "Countries which need the '
          'combined Geolocation plus SOS Popup" in the Market Configuration Table'],
         "NA",
         ["Bring the HU through the startup sequence",
          "Read the startup flow against the HMI to check which flow is followed"],
         ["The HU reaches the startup presentation",
          "The HU follows the Non-GDPR/Non-Maserati Startup flow in the HMI"],
         "P0", "本條驗 OR 之右支 country 未標記"),
    ],
    "SWE-PM-111": [
        ("A missing TBM adds the ADAS text to the disclaimer",
         [SIM, "The screen size is other than 7 inch",
          '$VC_VEH_BRAND$ reads a value other than "Maserati"',
          '$TBM_Present$ reads "Not Present"'],
         "NA",
         ["Bring the HU to the disclaimer presentation",
          "Read the disclaimer wording to check the added text"],
         ["The disclaimer screen is shown",
          "The HU adds the ADAS text to the disclaimer"],
         "P1", "本條驗 OR 之左支 TBM Not Present"),
        ("A country not requiring SOS or geolocation adds the ADAS text",
         [SIM, "The screen size is other than 7 inch",
          '$VC_VEH_BRAND$ reads a value other than "Maserati"',
          "$Country_Code$ does not require SOS or Geolocation"],
         "NA",
         ["Bring the HU to the disclaimer presentation",
          "Read the disclaimer wording to check the added text"],
         ["The disclaimer screen is shown",
          "The HU adds the ADAS text to the disclaimer"],
         "P1", "本條驗 OR 之右支 country 不需 SOS 或 Geolocation"),
    ],
    "SWE-PM-113": [
        ("A geolocation and SOS market adds the ADAS and SOS text",
         [SIM, "The screen size is other than 7 inch",
          '$VC_VEH_BRAND$ reads a value other than "Maserati"',
          '$TBM_Present$ reads "Present"',
          "$Country_Code$ requires geolocation and SOS in the disclaimer"],
         "NA",
         ["Bring the HU to the disclaimer presentation",
          "Read the shown wording to check what the HU adds"],
         ["The geolocation pop-up or the disclaimer is shown",
          "The HU adds the ADAS and SOS to the geolocation pop-up or disclaimer"],
         "P0", "本條驗 geolocation ＋ SOS 之附加"),
    ],
    "SWE-PM-114": [
        ("An incoming call from IDLE bypasses the not yet shown disclaimer screen",
         [SIM, "The HU is in IDLE mode", "The disclaimer screen has not yet been shown"],
         "An incoming phone call",
         ["Let the bench place the call listed in Input Test Data",
          "Read the HU mode and the screen to check whether the disclaimer appears"],
         ["The HU transitions from IDLE to FULL OPERATION",
          "The disclaimer screen is bypassed"],
         "P0", "本條驗來電所致之 IDLE → FULL OPERATION 免顯免責畫面"),
    ],
    "SWE-PM-115": [
        ("The disclaimer bypassed for a call is shown at the next FULL OPERATION",
         [SIM, "The HU is in IDLE mode", "The disclaimer has not yet been shown"],
         "An incoming phone call that then becomes inactive",
         ["Let the bench place and then end the call listed in Input Test Data",
          "Bring the HU to FULL OPERATION again and read the screen to check the disclaimer"],
         ["The HU bypasses the disclaimer for the call and returns to IDLE",
          "The disclaimer is shown at the next transition to FULL OPERATION"],
         "P0", "本條驗免責畫面之延後補顯"),
    ],
}


def numbered(items: list[str]) -> str:
    return "\n".join(f"{i}. {s}" for i, s in enumerate(items, 1))


def main() -> None:
    include, _ = scope()
    missing = [x for x in include if x not in TCS]
    extra = [x for x in TCS if x not in include]
    assert not missing and not extra, (missing, extra)

    l3, bodies = layer3(), anchor_bodies()
    ts = {r["leaf"]: r["test_set"]
          for r in csv.DictReader(
              (DATA / "leaf_batch_reconciliation.tsv").open(encoding="utf-8"),
              delimiter="\t")}
    leaves, tcs = [], []
    n = START_ID
    for leaf in include:
        rows = l3[leaf]
        anchors = [a for r in rows for a in r["item_ids"].split(",")
                   if a and bodies.get(a)]
        secs = sorted({r["chapter_num"] for r in rows})
        leaves.append({
            "parent": leaf,
            "section": "、".join(secs),
            "source_anchor": ",".join(anchors),
            "source_clause": "\n".join("\n".join(bodies[a]) for a in anchors),
            "reasoning": NOTES.get(leaf, ""),
        })
        for idx, (title, pre, data, proc, er, prio, reason) in enumerate(TCS[leaf], 1):
            tcs.append({
                "req_id": leaf,
                "tc_id": f"NR1L-PowerManagement-{n:03d}",
                "tc_title": title,
                "test_group": "Power Management",
                "test_set": ts[leaf],
                "test_item": title,
                "pre_conditions": numbered(pre),
                "input_test_data": data,
                "test_procedure": numbered(proc),
                "expected_result": numbered(er),
                "specification_reference": f"{SPEC}_{secs[0]}",
                "priority": prio,
                "design_method": "狀態轉換 (State Transition Testing)",
                "split_flag": len(TCS[leaf]) > 1,
                "split_reason": reason,
                "functional_safety": "NA",
                "estimated_test_time": "",
                "remarks": "",
                "distinguishing_axis": {"axis": "behaviour", "delta": reason},
                "reasoning_note": NOTES.get(leaf, ""),
                "split_index": idx,
            })
            n += 1

    batch = {
        "batch": BATCH,
        "test_group": "Power Management",
        "test_set": "Startup Display / Power State",
        "tc_id_status": "provisional",
        "tc_id_note": "R-P113(b)：本批之 `tc_id` 為批次內臨時號，接續第四批之末（157）。"
                      "JSON 陣列序維持遞增（§10.3 / G38）；寫回列序另由 "
                      "(SWE-PM ID, split_index) 決定。",
        "scope_note": "範圍**取自 G121 對帳表**（R-P177(b)，不以 ID 區間表述）："
                      f"Power State 未產出且未受阻斷者 ＋ Startup Display 未產出者，"
                      f"扣除撞上 live DR 影響面者（`SWE-PM-112` / DR-PW9，R-P181(c)）"
                      f"與已於第四批產出者（`SWE-PM-053`–`056`，R-P177(a) 不重做）。"
                      f"**本批 {len(leaves)} leaf**，leaf ID 全集見上繳 §四。",
        "leaves": leaves,
        "tcs": tcs,
    }
    path = GENERATED / f"{BATCH}.json"
    path.write_text(json.dumps(batch, ensure_ascii=False, indent=1) + "\n",
                    encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)} — {len(leaves)} leaf / {len(tcs)} TC "
          f"（{tcs[0]['tc_id']} – {tcs[-1]['tc_id']}）")


if __name__ == "__main__":
    main()
